version: "3.9"

services:
  app:
    build: .
    container_name: deshimtech_app
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "8082:8082"

  nginx:
    image: nginx:latest
    container_name: deshimtech_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: deshimtech_certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
    entrypoint: >
      sh -c "trap exit TERM;
      while :; do sleep 12h & wait $${!};
      certbot renew; done"